name: ci

on: [push, pull_request]

jobs:
  build:
    name: Running python ${{ matrix.python-version }} on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-mock
    - name: Install killport
      run: |
        pip install .
    - name: Run tests
      run: |
        pytest . -vv
